version: '3.8'

services:
  db:
    image: postgres:15
    container_name: arcane-postgres
    environment:
      POSTGRES_USER: arcane
      POSTGRES_PASSWORD: arcane_dev
      POSTGRES_DB: arcane_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
    name: arcane-postgres-data